Adding Neutron DB Tempest sanity checking
Fixes #841

Problem:
* Tests could potentially depend on a polluted state
  * Neutron settings and/or DB state
* Tests were silently dieing due to BIG-IP polluted state

Analysis:
* BIG-IP interaction elemeent enhanced to handle storing diffs
  * Each test differentiated by a uuid that is in the name of the diff file
  * This is provided in the assertion error traceback
Expected Example:
bigip_diff: /tmp/bigip_diff_9f69eb11-05b0-4783-93e9-8fa298140d02.cfg
* Neutron DB diffs are generated
Expected Example:
diff: /tmp/38e577f7-17fc-48de-b819-9fd64a832114.diff
Totaling:
AssertionError: Test was unable to clean up Neutron cfg (diff: /tmp/38e577f7-17fc-48de-b819-9fd64a832114.diff, bigip_diff: /tmp/bigip_diff_9f69eb11-05b0-4783-93e9-8fa298140d02.cfg)

Tests:
This is a major test enhancement and may result in a lot of tests flagged as problematic